### PR TITLE
fix(settings): fix undefined values for Chromium versions

### LINKED ISSUE #20: The "Settings" table is mostly "undefined" / "N/A" sinec February
If you click on the version number in the page header, a table comes up with the version / date / Chromium version. Since v2.1.1 in February, most (but not all) of the Chromium versions are listed as "undefined"
There's also an item at the top of the table right now that says "main - N/A - N/A"

### PR DESCRIPTION
**Pull request by theDavidBarton**
**Description:** Since a while there are `undefined` values in the Chromium column of the _Settings_ component. 
I summarized the cause of the problem here: https://github.com/puppeteer/pptr.dev/issues/20#issuecomment-776271813

**Before:**  ❌ 
before

**After:**  ✔️ 
after

@jackfranklin @johanbay can you take a look please? I am aware the fix is not perfect, but still better than how it looks now.  I will raise an issue in the [puppeteer repo](https://github.com/puppeteer/puppeteer) suggesting to use the Chromium versions in release notes that are recognized by the regex pattern.

_Note:_ I did not create **production build** as I faced issues with workbox-build: in case my PR would be accepted, please do the `npm run build` on the branch. (Was able to test the prod build anyway, only struggled with bumping the revision in sw.js 😅 )

closes #20

### CODE REVIEW

File: src/pptr/PPTRProduct.js [hunk 1]
```diff
@@ -102,6 +114,8 @@ export class PPTRProduct extends App.Product {
       const match = release.releaseNotes.match(/Chromium\s+(\d+\.\d+.\d+.\d+)\s*\((r\d{6})\)/i);
       if (match)
         release.chromiumVersion = `Chromium ${match[1]} (${match[2]})`;
+      else
```
Comment (mathiasbynens) [inline src/pptr/PPTRProduct.js:117]: Seems like we could try to match the new pattern here before falling back to N/A. That way we wouldn’t have to hardcode the above versions. WDYT?

Comment (mathiasbynens) [reply src/pptr/PPTRProduct.js:117]: Ah, you're right, we'd still need it to map the revisions to the exact version. Seems fine to do it this way then + change `CONTRIBUTING.md` to include the Chromium version in the commit message as well 👍

**Review by mathiasbynens — APPROVED** [review]

**Comment by theDavidBarton** [comment]
Thanks for taking care of this @mathiasbynens 👍 

I think the only thing that remained here is to do a production build as well, I did not create one back then as I faced issues with workbox-build: can someone please do the `npm run build` on the branch. (Change was tested on a prod build anyway, I only struggled with bumping the revision in **sw.js** 😅 ).  
Apology if I did not emphasize this more loudly before. I am neither sure if it needs to be deployed manually, as there is no CI set up for the repo.

**Comment by mathiasbynens** [comment]
It looks like the `docs` folder in the `master` branch is the source of truth that's served directly on <https://pptr.dev/>. I’ve just re-generated the docs and pushed it.

**Comment by theDavidBarton** [comment]
Perfect, thank you!

**Comment by mathiasbynens** [comment]
Thanks for the patch and follow-up!
